bot:
  token: discordToken

discord:
  roleID: 0
  channelID: 0
  guildID: 0

timings: # in minutes
  user:
    expire-in: 7200
    check-expiration: 60
  token:
    expire-in: 5

unrestricted:
  - hopperW12
  - novosadkry
